import type {
  AgentToolApprovalSettings,
  AgentToolDefinition,
  AgentToolId,
  AgentToolPackageDefinition,
  AgentToolSettings,
} from '../../shared/types';

export const FORGER_TOOL_PACKAGE_ID = 'forger';

export const AGENT_TOOL_PACKAGES: AgentToolPackageDefinition[] = [
  {
    id: FORGER_TOOL_PACKAGE_ID,
    name: 'Forger',
    description: 'Built-in tools included with the Forger desktop application.',
    icon: 'forger',
    tools: [
      {
        id: 'forger_list_catalog',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Obtener catalogo',
        description: 'Revisa las apps publicadas y sus versiones disponibles.',
        category: 'consulta',
        risk: 'bajo',
        defaultRequiresApproval: false,
      },
      {
        id: 'forger_list_installed_apps',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Listar apps instaladas',
        description: 'Consulta que apps estan instaladas y su estado actual.',
        category: 'consulta',
        risk: 'bajo',
        defaultRequiresApproval: false,
      },
      {
        id: 'forger_check_updates',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Revisar actualizaciones',
        description: 'Compara versiones instaladas con el catalogo publicado.',
        category: 'consulta',
        risk: 'bajo',
        defaultRequiresApproval: false,
      },
      {
        id: 'forger_list_app_prompts',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Listar prompts de app',
        description: 'Revisa los prompts declarados por una app instalada y si tienen cambios locales.',
        category: 'consulta',
        risk: 'bajo',
        defaultRequiresApproval: false,
      },
      {
        id: 'forger_test_app_prompt',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Probar prompt de app',
        description: 'Valida y renderiza un prompt declarado por una app instalada sin guardarlo ni ejecutarlo.',
        category: 'consulta',
        risk: 'bajo',
        defaultRequiresApproval: false,
      },
      {
        id: 'forger_update_app_prompt',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Editar prompt de app',
        description: 'Actualiza un prompt local de una app instalada despues de validar sus variables.',
        category: 'app',
        risk: 'medio',
        defaultRequiresApproval: true,
      },
      {
        id: 'forger_restore_app_prompt',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Restaurar prompt de app',
        description: 'Restaura el prompt original declarado por una app instalada.',
        category: 'app',
        risk: 'medio',
        defaultRequiresApproval: true,
      },
      {
        id: 'memory_list',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Consultar memoria',
        description: 'Consulta preferencias y notas guardadas en la memoria local de Forger.',
        category: 'memoria',
        risk: 'bajo',
        defaultRequiresApproval: false,
      },
      {
        id: 'memory_create',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Guardar memoria',
        description: 'Guarda una preferencia o nota util en la memoria local de Forger.',
        category: 'memoria',
        risk: 'bajo',
        defaultRequiresApproval: false,
      },
      {
        id: 'memory_update',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Actualizar memoria',
        description: 'Actualiza una preferencia o nota guardada en la memoria local de Forger.',
        category: 'memoria',
        risk: 'bajo',
        defaultRequiresApproval: false,
      },
      {
        id: 'memory_delete',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Eliminar memoria',
        description: 'Elimina una preferencia o nota guardada en la memoria local de Forger.',
        category: 'memoria',
        risk: 'bajo',
        defaultRequiresApproval: false,
      },
      {
        id: 'forger_get_app_runtime_status',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Consultar estado de app',
        description: 'Revisa si una app esta abierta, detenida o requiere atencion.',
        category: 'consulta',
        risk: 'bajo',
        defaultRequiresApproval: false,
      },
      {
        id: 'forger_open_app',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Abrir app',
        description: 'Inicia una app instalada y abre su ventana.',
        category: 'app',
        risk: 'medio',
        defaultRequiresApproval: true,
      },
      {
        id: 'forger_stop_app',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Cerrar app',
        description: 'Detiene una app abierta y cierra sus servicios locales.',
        category: 'app',
        risk: 'medio',
        defaultRequiresApproval: true,
      },
      {
        id: 'forger_restart_app',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Reiniciar app',
        description: 'Cierra y vuelve a abrir una app instalada.',
        category: 'app',
        risk: 'medio',
        defaultRequiresApproval: true,
      },
      {
        id: 'forger_refresh_app_view',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Refrescar vista',
        description: 'Refresca la ventana de una app que ya esta abierta.',
        category: 'vista',
        risk: 'medio',
        defaultRequiresApproval: true,
      },
      {
        id: 'forger_update_app',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Actualizar app',
        description: 'Aplica una nueva version publicada cuando esta disponible.',
        category: 'actualizacion',
        risk: 'alto',
        defaultRequiresApproval: true,
      },
    ],
  },
  {
    id: 'official:gmail',
    name: 'Gmail',
    description: 'Herramienta oficial para buscar, leer y enviar correos de Gmail.',
    icon: 'forger',
    tools: [
      {
        id: 'gmail.connection.status',
        packageId: 'official:gmail',
        name: 'Estado de Gmail',
        description: 'Revisa si la cuenta de Gmail esta conectada.',
        category: 'consulta',
        risk: 'bajo',
        defaultRequiresApproval: false,
      },
      {
        id: 'gmail.search_messages',
        packageId: 'official:gmail',
        name: 'Buscar correos',
        description: 'Busca correos de Gmail usando una consulta.',
        category: 'consulta',
        risk: 'medio',
        defaultRequiresApproval: true,
      },
      {
        id: 'gmail.read_thread',
        packageId: 'official:gmail',
        name: 'Leer correo',
        description: 'Lee una conversacion o mensaje de Gmail e identifica adjuntos.',
        category: 'consulta',
        risk: 'alto',
        defaultRequiresApproval: true,
      },
      {
        id: 'gmail.read_attachment',
        packageId: 'official:gmail',
        name: 'Leer adjunto',
        description: 'Descarga un adjunto de Gmail para que el agente pueda revisarlo o reutilizarlo.',
        category: 'consulta',
        risk: 'alto',
        defaultRequiresApproval: true,
      },
      {
        id: 'gmail.send_email',
        packageId: 'official:gmail',
        name: 'Enviar correo',
        description: 'Envia un correo desde Gmail.',
        category: 'app',
        risk: 'alto',
        defaultRequiresApproval: true,
      },
    ],
  },
];

export const AGENT_TOOL_DEFINITIONS: AgentToolDefinition[] = AGENT_TOOL_PACKAGES.flatMap((toolPackage) => toolPackage.tools);

export const AGENT_TOOL_IDS = new Set<AgentToolId>(AGENT_TOOL_DEFINITIONS.map((tool) => tool.id));

export const createInitialAgentToolSettings = (): AgentToolSettings => ({
  approvals: AGENT_TOOL_DEFINITIONS.reduce((acc, tool) => {
    acc[tool.id] = tool.defaultRequiresApproval;
    return acc;
  }, {} as AgentToolApprovalSettings),
});
