import type {
  AgentToolApprovalSettings,
  AgentToolDefinition,
  AgentToolId,
  AgentToolPackageDefinition,
  AgentToolSettings,
} from '../../shared/types';
import { getSharedCopy } from '../../shared/i18n';

export const FORGER_TOOL_PACKAGE_ID = 'forger';

export const AGENT_TOOL_PACKAGES: AgentToolPackageDefinition[] = [
  {
    id: FORGER_TOOL_PACKAGE_ID,
    name: 'Forger',
    description: 'Built-in tools included with the Forger desktop application.',
    icon: 'forger',
    tools: [
      {
        id: 'forger_list_catalog',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Obtener catalogo',
        description: 'Revisa las apps publicadas y sus versiones disponibles.',
        category: 'consulta',
        risk: 'bajo',
        defaultRequiresApproval: false,
      },
      {
        id: 'forger_list_installed_apps',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Listar apps instaladas',
        description: 'Consulta que apps estan instaladas y su estado actual.',
        category: 'consulta',
        risk: 'bajo',
        defaultRequiresApproval: false,
      },
      {
        id: 'forger_check_updates',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Revisar actualizaciones',
        description: 'Compara versiones instaladas con el catalogo publicado.',
        category: 'consulta',
        risk: 'bajo',
        defaultRequiresApproval: false,
      },
      {
        id: 'forger_create_app',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Crear app',
        description: 'Crea una nueva app local desde una especificacion conversada con la persona.',
        category: 'app',
        risk: 'medio',
        defaultRequiresApproval: false,
      },
      {
        id: 'forger_add_app_to_personal_agent',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Agregar app al agente',
        description: 'Permite que el agente personal cargue el MCP de una app instalada en sus proximas ejecuciones.',
        category: 'app',
        risk: 'medio',
        defaultRequiresApproval: false,
      },
      {
        id: 'forger_request_app_tool_grant',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Permitir herramienta opcional',
        description: 'Solicita a la persona activar para una app una herramienta oficial opcional ya declarada en su manifest.',
        category: 'app',
        risk: 'medio',
        defaultRequiresApproval: false,
      },
      {
        id: 'forger_list_app_prompts',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Listar prompts de app',
        description: 'Revisa los prompts declarados por una app instalada y si tienen cambios locales.',
        category: 'consulta',
        risk: 'bajo',
        defaultRequiresApproval: false,
      },
      {
        id: 'forger_test_app_prompt',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Probar prompt de app',
        description: 'Valida y renderiza un prompt declarado por una app instalada sin guardarlo ni ejecutarlo.',
        category: 'consulta',
        risk: 'bajo',
        defaultRequiresApproval: false,
      },
      {
        id: 'forger_update_app_prompt',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Editar prompt de app',
        description: 'Actualiza un prompt local de una app instalada despues de validar sus variables.',
        category: 'app',
        risk: 'medio',
        defaultRequiresApproval: true,
      },
      {
        id: 'forger_restore_app_prompt',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Restaurar prompt de app',
        description: 'Restaura el prompt original declarado por una app instalada.',
        category: 'app',
        risk: 'medio',
        defaultRequiresApproval: true,
      },
      {
        id: 'forger_speech_to_text_status',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Estado de Speech to text',
        description: 'Revisa si el servicio local de transcripcion esta instalado y listo.',
        category: 'consulta',
        risk: 'bajo',
        defaultRequiresApproval: false,
      },
      {
        id: 'forger_transcribe_audio',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Transcribir audio',
        description: 'Transcribe un archivo de audio compartido o autorizado por Forger.',
        category: 'consulta',
        risk: 'medio',
        defaultRequiresApproval: true,
      },
      {
        id: 'forger_translate_audio',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Traducir audio',
        description: 'Traduce a texto en ingles un archivo de audio compartido o autorizado por Forger.',
        category: 'consulta',
        risk: 'medio',
        defaultRequiresApproval: true,
      },
      {
        id: 'forger_text_to_speech_status',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Estado de Text to speech',
        description: 'Revisa si el servicio local de sintesis de voz esta instalado y listo.',
        category: 'consulta',
        risk: 'bajo',
        defaultRequiresApproval: false,
      },
      {
        id: 'forger_text_to_speech_voices',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Voces de Text to speech',
        description: 'Lista los modelos y voces locales cargadas para sintetizar voz.',
        category: 'consulta',
        risk: 'bajo',
        defaultRequiresApproval: false,
      },
      {
        id: 'forger_synthesize_speech',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Sintetizar voz',
        description: 'Genera audio local desde texto usando el modelo y voz solicitados.',
        category: 'consulta',
        risk: 'medio',
        defaultRequiresApproval: true,
      },
      {
        id: 'forger_get_app_runtime_status',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Consultar estado de app',
        description: 'Revisa si una app esta abierta, detenida o requiere atencion.',
        category: 'consulta',
        risk: 'bajo',
        defaultRequiresApproval: false,
      },
      {
        id: 'forger_get_app_view_snapshot',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Capturar vista de app',
        description: 'Lee un snapshot textual seguro de la ventana Forger de una app abierta para diagnosticar UI sin abrir URLs internas en Chrome.',
        category: 'consulta',
        risk: 'bajo',
        defaultRequiresApproval: false,
      },
      {
        id: 'forger_get_app_runtime_diagnostics',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Diagnostico runtime de app',
        description: 'Revisa estado, ventana y logs recientes de una app instalada sin exponer secretos ni abrir URLs internas.',
        category: 'consulta',
        risk: 'bajo',
        defaultRequiresApproval: false,
      },
      {
        id: 'forger_open_app',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Abrir app',
        description: 'Inicia una app instalada y abre su ventana.',
        category: 'app',
        risk: 'medio',
        defaultRequiresApproval: true,
      },
      {
        id: 'forger_stop_app',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Cerrar app',
        description: 'Detiene una app abierta y cierra sus servicios locales.',
        category: 'app',
        risk: 'medio',
        defaultRequiresApproval: true,
      },
      {
        id: 'forger_restart_app',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Reiniciar app',
        description: 'Cierra y vuelve a abrir una app instalada.',
        category: 'app',
        risk: 'medio',
        defaultRequiresApproval: true,
      },
      {
        id: 'forger_refresh_app_view',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Refrescar vista',
        description: 'Refresca la ventana de una app que ya esta abierta.',
        category: 'vista',
        risk: 'medio',
        defaultRequiresApproval: true,
      },
      {
        id: 'forger_update_app',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Actualizar app',
        description: 'Aplica una nueva version publicada cuando esta disponible.',
        category: 'actualizacion',
        risk: 'alto',
        defaultRequiresApproval: true,
      },
      {
        id: 'forger_update_published_app_info',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Editar info publicada',
        description: 'Actualiza nombre, descripcion, categoria o visibilidad de una app publicada en Social.',
        category: 'app',
        risk: 'medio',
        defaultRequiresApproval: true,
      },
      {
        id: 'forger_workflow_list',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Listar flujos',
        description: 'Revisa los flujos de trabajo definidos, su estado y su ultima ejecucion.',
        category: 'consulta',
        risk: 'bajo',
        defaultRequiresApproval: false,
      },
      {
        id: 'forger_workflow_get',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Ver flujo',
        description: 'Lee la definicion completa de un flujo de trabajo: nodos, conexiones y trigger.',
        category: 'consulta',
        risk: 'bajo',
        defaultRequiresApproval: false,
      },
      {
        id: 'forger_workflow_upsert',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Crear o editar flujo',
        description: 'Crea o actualiza un flujo de trabajo con nodos de agente, conectores y condiciones.',
        category: 'app',
        risk: 'medio',
        defaultRequiresApproval: true,
      },
      {
        id: 'forger_workflow_run',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Ejecutar flujo',
        description: 'Ejecuta un flujo de trabajo existente y devuelve el resumen de la ejecucion.',
        category: 'app',
        risk: 'medio',
        defaultRequiresApproval: true,
      },
      {
        id: 'forger_finish_social_app_install',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Finalizar instalacion Social',
        description: 'Aprueba una app Social descargada en cuarentena y completa su instalacion local.',
        category: 'app',
        risk: 'alto',
        defaultRequiresApproval: true,
      },
      {
        id: 'forger_delete_quarantined_social_app',
        packageId: FORGER_TOOL_PACKAGE_ID,
        name: 'Eliminar app en cuarentena',
        description: 'Elimina los archivos locales de una app Social descargada solo para revision.',
        category: 'app',
        risk: 'alto',
        defaultRequiresApproval: true,
      },
    ],
  },
  {
    id: 'official:forger_chrome_extension',
    name: 'Forger Chrome Extension',
    description: 'Herramienta oficial para operar una ventana dedicada de Chrome con la extension local de Forger.',
    icon: 'forger',
    tools: [
      {
        id: 'forger_chrome_extension.connection.status',
        packageId: 'official:forger_chrome_extension',
        name: 'Estado de Chrome',
        description: 'Revisa si la extension de Chrome esta conectada.',
        category: 'consulta',
        risk: 'bajo',
        defaultRequiresApproval: false,
      },
      {
        id: 'forger_chrome_extension.open_dedicated_tab',
        packageId: 'official:forger_chrome_extension',
        name: 'Abrir Chrome dedicado',
        description: 'Crea una ventana y pestaña de Chrome controlada por Forger.',
        category: 'vista',
        risk: 'medio',
        defaultRequiresApproval: true,
      },
      {
        id: 'forger_chrome_extension.get_current_url',
        packageId: 'official:forger_chrome_extension',
        name: 'Leer URL de Chrome',
        description: 'Lee la URL actual de una sesion dedicada de Chrome.',
        category: 'consulta',
        risk: 'bajo',
        defaultRequiresApproval: false,
      },
      {
        id: 'forger_chrome_extension.navigate',
        packageId: 'official:forger_chrome_extension',
        name: 'Navegar en Chrome',
        description: 'Navega una sesion dedicada de Chrome a una URL http o https.',
        category: 'vista',
        risk: 'medio',
        defaultRequiresApproval: true,
      },
      {
        id: 'forger_chrome_extension.get_html',
        packageId: 'official:forger_chrome_extension',
        name: 'Leer HTML',
        description: 'Lee HTML de la pagina completa o de un selector.',
        category: 'consulta',
        risk: 'alto',
        defaultRequiresApproval: true,
      },
      {
        id: 'forger_chrome_extension.wait_for_selector',
        packageId: 'official:forger_chrome_extension',
        name: 'Esperar selector',
        description: 'Espera hasta que un selector alcance un estado visible, oculto, adjunto o removido.',
        category: 'consulta',
        risk: 'bajo',
        defaultRequiresApproval: false,
      },
      {
        id: 'forger_chrome_extension.click',
        packageId: 'official:forger_chrome_extension',
        name: 'Click en Chrome',
        description: 'Hace click en un elemento encontrado por selector.',
        category: 'vista',
        risk: 'medio',
        defaultRequiresApproval: true,
      },
      {
        id: 'forger_chrome_extension.focus',
        packageId: 'official:forger_chrome_extension',
        name: 'Enfocar elemento',
        description: 'Enfoca un elemento encontrado por selector.',
        category: 'vista',
        risk: 'medio',
        defaultRequiresApproval: true,
      },
      {
        id: 'forger_chrome_extension.hover',
        packageId: 'official:forger_chrome_extension',
        name: 'Hover en elemento',
        description: 'Dispara eventos de hover sobre un elemento encontrado por selector.',
        category: 'vista',
        risk: 'medio',
        defaultRequiresApproval: true,
      },
      {
        id: 'forger_chrome_extension.input_text',
        packageId: 'official:forger_chrome_extension',
        name: 'Escribir en Chrome',
        description: 'Escribe texto en un input o elemento editable encontrado por selector.',
        category: 'vista',
        risk: 'alto',
        defaultRequiresApproval: true,
      },
      {
        id: 'forger_chrome_extension.submit_form',
        packageId: 'official:forger_chrome_extension',
        name: 'Enviar formulario',
        description: 'Envía el formulario asociado a un elemento encontrado por selector.',
        category: 'vista',
        risk: 'alto',
        defaultRequiresApproval: true,
      },
      {
        id: 'forger_chrome_extension.get_styles',
        packageId: 'official:forger_chrome_extension',
        name: 'Leer estilos',
        description: 'Lee estilos CSS computados e inline de un elemento encontrado por selector.',
        category: 'consulta',
        risk: 'bajo',
        defaultRequiresApproval: false,
      },
      {
        id: 'forger_chrome_extension.set_styles',
        packageId: 'official:forger_chrome_extension',
        name: 'Destacar elemento',
        description: 'Aplica estilos CSS permitidos a un elemento para destacarlo visualmente.',
        category: 'vista',
        risk: 'medio',
        defaultRequiresApproval: true,
      },
      {
        id: 'forger_chrome_extension.close_window',
        packageId: 'official:forger_chrome_extension',
        name: 'Cerrar ventana de Chrome',
        description: 'Cierra la ventana dedicada de Chrome asociada a una sesion.',
        category: 'vista',
        risk: 'medio',
        defaultRequiresApproval: true,
      },
      {
        id: 'forger_chrome_extension.close_session',
        packageId: 'official:forger_chrome_extension',
        name: 'Cerrar Chrome dedicado',
        description: 'Cierra una ventana dedicada de Chrome controlada por Forger.',
        category: 'vista',
        risk: 'medio',
        defaultRequiresApproval: true,
      },
    ],
  },
];

export const getAgentToolPackages = (locale?: string | null): AgentToolPackageDefinition[] => {
  const chromeExtensionCopy = getSharedCopy(locale).officialTools.forger_chrome_extension;
  return AGENT_TOOL_PACKAGES.map((toolPackage) => {
    if (toolPackage.id !== 'official:forger_chrome_extension') {
      return toolPackage;
    }
    return {
      ...toolPackage,
      name: chromeExtensionCopy.name,
      description: chromeExtensionCopy.description,
      tools: toolPackage.tools.map((tool) => {
        const actionCopy = (chromeExtensionCopy.actions as Partial<Record<AgentToolId, { name: string; description: string }>>)[tool.id];
        return actionCopy
          ? { ...tool, name: actionCopy.name, description: actionCopy.description }
          : tool;
      }),
    };
  });
};

const MEMORY_TOOL_DEFINITIONS: AgentToolDefinition[] = [
  {
    id: 'memory_list',
    packageId: 'platform:memory',
    name: 'Consultar memoria',
    description: 'Consulta preferencias y notas guardadas en la memoria local de Forger.',
    category: 'memoria',
    risk: 'bajo',
    defaultRequiresApproval: false,
  },
  {
    id: 'memory_create',
    packageId: 'platform:memory',
    name: 'Guardar memoria',
    description: 'Guarda una preferencia o nota util en la memoria local de Forger.',
    category: 'memoria',
    risk: 'bajo',
    defaultRequiresApproval: false,
  },
  {
    id: 'memory_update',
    packageId: 'platform:memory',
    name: 'Actualizar memoria',
    description: 'Actualiza una preferencia o nota guardada en la memoria local de Forger.',
    category: 'memoria',
    risk: 'bajo',
    defaultRequiresApproval: false,
  },
  {
    id: 'memory_delete',
    packageId: 'platform:memory',
    name: 'Eliminar memoria',
    description: 'Elimina una preferencia o nota guardada en la memoria local de Forger.',
    category: 'memoria',
    risk: 'bajo',
    defaultRequiresApproval: false,
  },
];

export const AGENT_TOOL_DEFINITIONS: AgentToolDefinition[] = [
  ...AGENT_TOOL_PACKAGES.flatMap((toolPackage) => toolPackage.tools),
  ...MEMORY_TOOL_DEFINITIONS,
];

export const AGENT_TOOL_IDS = new Set<AgentToolId>(AGENT_TOOL_DEFINITIONS.map((tool) => tool.id));

export const createInitialAgentToolSettings = (): AgentToolSettings => ({
  approvals: AGENT_TOOL_DEFINITIONS.reduce((acc, tool) => {
    acc[tool.id] = tool.defaultRequiresApproval;
    return acc;
  }, {} as AgentToolApprovalSettings),
});
