import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

interface IsolatedCodexHomeOptions {
  prefix: string;
  trustedRoots: string[];
  networkAccess?: boolean;
}

interface PersistentCodexHomeOptions {
  trustedRoots: string[];
  networkAccess?: boolean;
}

export class DisallowedMcpServerError extends Error {
  public constructor(public readonly serverName: string) {
    super(`disallowed_mcp_server:${serverName}`);
    this.name = 'DisallowedMcpServerError';
  }
}

export const codexWorkspaceNetworkConfigArgs = (networkAccess: boolean): string[] =>
  networkAccess ? ['--config', 'sandbox_workspace_write.network_access=true'] : [];

export const createIsolatedCodexHome = async (
  sourceCodexHome: string,
  options: IsolatedCodexHomeOptions,
): Promise<string> => {
  const targetCodexHome = await fs.mkdtemp(path.join(os.tmpdir(), `${options.prefix}-`));
  await copyCodexHomeFile(path.join(sourceCodexHome, 'auth.json'), path.join(targetCodexHome, 'auth.json'));
  await fs.writeFile(path.join(targetCodexHome, 'config.toml'), buildIsolatedConfig(options.trustedRoots, options.networkAccess === true), {
    encoding: 'utf8',
    mode: 0o600,
  });
  return targetCodexHome;
};

export const preparePersistentIsolatedCodexHome = async (
  sourceCodexHome: string,
  targetCodexHome: string,
  options: PersistentCodexHomeOptions,
): Promise<string> => {
  await fs.mkdir(targetCodexHome, { recursive: true, mode: 0o700 });
  await copyCodexHomeFile(path.join(sourceCodexHome, 'auth.json'), path.join(targetCodexHome, 'auth.json'));
  await fs.writeFile(path.join(targetCodexHome, 'config.toml'), buildIsolatedConfig(options.trustedRoots, options.networkAccess === true), {
    encoding: 'utf8',
    mode: 0o600,
  });
  return targetCodexHome;
};

export const removeIsolatedCodexHome = async (codexHome: string | null | undefined): Promise<void> => {
  if (!codexHome || !path.basename(codexHome).startsWith('forger-')) {
    return;
  }
  await fs.rm(codexHome, { recursive: true, force: true }).catch(() => undefined);
};

export const assertAllowedMcpServers = (stdout: string, stderr: string, allowedServers: Set<string>): void => {
  const allowedServerNames = expandAllowedMcpServerNames(allowedServers);
  for (const line of `${stdout}\n${stderr}`.split('\n').map((entry) => entry.trim()).filter(Boolean)) {
    let parsed: Record<string, unknown>;
    try {
      parsed = JSON.parse(line) as Record<string, unknown>;
    } catch {
      continue;
    }
    const item = parsed.item && typeof parsed.item === 'object' ? parsed.item as Record<string, unknown> : null;
    const itemType = typeof item?.type === 'string' ? item.type : '';
    if (itemType !== 'mcp_tool_call') {
      continue;
    }
    const server = typeof item?.server === 'string' ? item.server.trim() : '';
    if (server && !allowedServerNames.has(server)) {
      throw new DisallowedMcpServerError(server);
    }
  }
};

const expandAllowedMcpServerNames = (allowedServers: Set<string>): Set<string> => {
  const expanded = new Set<string>();
  for (const server of allowedServers) {
    expanded.add(server);
    const normalized = server.replace(/[^a-zA-Z0-9]/g, '_');
    expanded.add(`mcp_${normalized}__`);
    expanded.add(`mcp_${normalized.toLowerCase()}__`);
  }
  return expanded;
};

const copyCodexHomeFile = async (sourcePath: string, targetPath: string): Promise<void> => {
  try {
    await fs.copyFile(sourcePath, targetPath);
    await fs.chmod(targetPath, 0o600).catch(() => undefined);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
      throw error;
    }
  }
};

const buildIsolatedConfig = (trustedRoots: string[], networkAccess: boolean): string => {
  const uniqueRoots = [...new Set(trustedRoots.map((root) => path.resolve(root)))];
  const networkLines = networkAccess
    ? [
        '[sandbox_workspace_write]',
        'network_access = true',
        '',
      ]
    : [];
  return [
    '# Generated by Forger. Do not inherit user Codex plugins or MCP servers in Forger runs.',
    '',
    ...networkLines,
    ...uniqueRoots.flatMap((root) => [
      `[projects.${JSON.stringify(root)}]`,
      'trust_level = "trusted"',
      '',
    ]),
  ].join('\n');
};
