import type { AppSummary } from './catalog';
import type { CatalogApp } from './catalog-app';
import type { CreateLocalAppInput, CreateLocalAppResult, InstallAppResult, LocalNetworkShareResult, LocalNetworkShareStatus, OpenAppResult, RemoteNetworkShareResult, RemoteNetworkShareStatus, StopAppResult, RuntimeStatus } from './runtime';
import type { BasicActionResult } from './base';
import type { AppBackupSummary, CreateAppBackupInput, CreateAppBackupResult, DeleteAppBackupBatchInput, DeleteAppBackupBatchResult, DeleteAppBackupInput, RestoreAppBackupInput, RemoteBackupsState, CreateRemoteAppBackupInput, CreateRemoteAppBackupResult, RestoreRemoteAppBackupInput, CloudSyncSettings } from './backups';
import type { AppDetails, ChatRunStatus, ChatRun, ChatRunEvent, ChatStartRunInput, ChatGetRunInput, ChatCancelRunInput, ChatApprovePermissionInput, ChatApplyRunInput, ChatApplyResult, ChatUndoInput, ChatUndoResult, RendererChatTraceEvent } from './chat';
import type { AppPromptMutationResult, AppPromptRestoreInput, AppPromptReviewInput, AppPromptReviewItem, AppPromptValidationResult } from './prompts';
import type { InstallWelcomeResult } from './chat';
import type { AppSecretsState, UserSecretSummary, CreateUserSecretInput, UpdateUserSecretInput, DeleteUserSecretInput, ConnectAppSecretInput, DisconnectAppSecretInput, SecretMutationResult } from './secrets';
import type { DeveloperPathState, Settings, UpdateAppDeveloperSettingsInput, UpdateCodexDefaultsInput, UpdateDeveloperModeInput, UpdateAgentDefaultsInput, MemoryListInput, MemoryEntry, MemoryCreateInput, MemoryUpdateInput } from './settings';
import type { SpeechToTextConfigInput, SpeechToTextProcessInput, SpeechToTextProcessResult, SpeechToTextRealtimeSession, SpeechToTextState, SpeechToTextUploadInput } from './speech-to-text';
import type { TextToSpeechConfigInput, TextToSpeechState, TextToSpeechSynthesizeInput, TextToSpeechSynthesizeResult } from './text-to-speech';
import type { LiveVoiceInputConfigInput, LiveVoiceInputDeviceListInput, LiveVoiceInputSession, LiveVoiceInputSessionInput, LiveVoiceInputState, LiveVoiceInputStopInput, LiveVoiceInputWakeEvent, LiveVoiceInputWakeRuntime } from './live-voice-input';
import type { WakeWordConfigInput, WakeWordDetectionEvent, WakeWordDiagnosticEvent, WakeWordRuntime, WakeWordSession, WakeWordState } from './wake-word';
import type { AudioRuntimeBrokerRequest, AudioRuntimeBrokerResponse } from './audio-runtime';
import type { DesktopUpdateState } from './updates';
import type { ForgerAccountSession, ForgerAccountRegisterInput, ForgerAccountLoginInput, ForgerAccountProfileInput, CloudDevicesState } from './account';
import type { CloudStorageUsage } from './cloud-storage';
import type { FriendChatWindowOpenResult, CloudFriendship, CloudFriendUser, CloudMessage, CloudSendAppShareInput, CloudSendMessageInput, CloudAppMessagePermissionDecision, CloudSocialEvent, CloudIdentityState, ForumComment, ForumParticipationState, ForumPost, PrepareSocialAppReviewInput, SocialAppQuarantineRecord, SocialUserApp, SocialUserAppDownload, SocialUserAppList, SocialUserAppShare, SocialUserAppUpdateInput, SocialUserAppUploadInput, SocialUserAppVisibility, SocialUserProfileDetail } from './social';
import type { AppRatingSummary, SubmitAppRatingInput, SubmitProductFeedbackInput } from './feedback';
import type { SubmitUsageEventInput, SubmitUsageEventResult } from './usage-events';
import type { ConversationDiagnosticReportPreview, PrepareConversationDiagnosticReportInput, SubmitConversationDiagnosticReportResult } from './diagnostics';
import type { FailureDiagnosticFields } from './base';
import type { AntigravityAuthSessionEvent, AntigravityAuthSessionStartResult, AntigravityAuthStatus, CodexAuthStatus, ClaudeAuthStatus, DesktopErrorReportPreview } from './auth';
import type { AgentProviderUsageResult } from './provider-usage';
import type { LlmProviderProfileMutationResult, LlmProviderProfilesState, SetActiveLlmProviderProfileInput, SetActiveLlmProviderProfileResult, UpdateLlmProviderProfileDefaultsInput } from './provider-profiles';
import type { AgentToolPackageDefinition, AgentToolSettings, UpdateAgentToolApprovalInput, OfficialToolsState, ToolMutationResult, ConfigureOfficialToolInput, CallOfficialToolInput, CallOfficialToolResult, AppToolsInstallGate, SetAppToolGrantInput, OfficialToolRuntimeEvent, GetAppToolsInstallGateOptions } from './tools';
import type { CallConnectionActionInput, CallConnectionActionResult, ConfigureConnectionInput, ConnectionMutationResult, ConnectionsState, DisconnectConnectionInput } from './connections';
import type { PickedChatFile, FilesStageForChatInput, FilesDiscardStagedForChatInput, FilesActionResult, FilesListInput, ForgerFileRecord, ForgerFileCategory, FilesCreateCategoryInput, FilesRenameCategoryInput, FilesDeleteCategoryInput, FilesImportInput, FilesMoveInput, FilesRenameInput, FilesDeleteInput, DbListTablesResponse, DbQueryTableResponse } from './data';
import type { Automation, AutomationRun, AutomationRunSummary, AutomationUpsertInput, WindowControlState } from './automations';
import type { Workflow, WorkflowApproveNodeInput, WorkflowRun, WorkflowRunSummary, WorkflowUpdatedEvent, WorkflowUpsertInput } from './workflows';
import type { BackgroundTask, BackgroundTaskEvent, BackgroundTaskUpsertInput } from './background-tasks';
import type { LlmRunsSnapshot } from './llm-runs';
import type { PersonalAgent, PersonalAgentConversation, PersonalAgentConversationEvent, PersonalAgentConversationGetInput, PersonalAgentConversationsListInput, PersonalAgentConversationStartInput, PersonalAgentCreateInput, PersonalAgentDeleteInput, PersonalAgentGrantOptions, PersonalAgentMessageSendInput, PersonalAgentPeerThread, PersonalAgentPeerThreadGetInput, PersonalAgentPeerThreadsListInput, PersonalAgentUpdatePermissionsInput, PersonalAgentWorkspaceEntry, PersonalAgentWorkspaceFile, PersonalAgentWorkspaceFileReadInput, PersonalAgentWorkspaceFileWriteInput, PersonalAgentWorkspaceListInput } from './personal-agents';
import type { RemoteActivitySnapshot } from './remote-activity';

export type MicrophonePermissionStatus = 'not-determined' | 'granted' | 'denied' | 'restricted' | 'unknown' | 'unsupported';

export interface RenameInstalledAppInput {
  appId: string;
  name: string;
}

export interface RenameInstalledAppResult extends BasicActionResult {
  app?: AppSummary;
  cloudSynced?: boolean;
}

export interface ForgerDesktopApi {
  listInstalledApps: () => Promise<AppSummary[]>;
  listCatalogApps: () => Promise<CatalogApp[]>;
  installApp: (appId: string, locale?: string) => Promise<InstallAppResult>;
  createLocalApp: (input: CreateLocalAppInput, locale?: string) => Promise<CreateLocalAppResult>;
  updateApp: (appId: string, locale?: string) => Promise<InstallAppResult>;
  listBackups: (appId?: string) => Promise<AppBackupSummary[]>;
  createBackup: (input: CreateAppBackupInput) => Promise<CreateAppBackupResult>;
  deleteBackup: (input: DeleteAppBackupInput) => Promise<BasicActionResult>;
  deleteBackups: (input: DeleteAppBackupBatchInput) => Promise<DeleteAppBackupBatchResult>;
  restoreBackup: (input: RestoreAppBackupInput) => Promise<BasicActionResult>;
  listRemoteBackups: (appId?: string) => Promise<RemoteBackupsState>;
  createRemoteBackup: (input: CreateRemoteAppBackupInput) => Promise<CreateRemoteAppBackupResult>;
  deleteRemoteBackup: (remoteBackupId: number) => Promise<BasicActionResult>;
  restoreRemoteBackup: (input: RestoreRemoteAppBackupInput) => Promise<BasicActionResult>;
  getCloudSyncSettings: () => Promise<CloudSyncSettings>;
  setAppAutoSync: (appId: string, autoSync: boolean) => Promise<CloudSyncSettings>;
  restoreAppUserVersion: (appId: string) => Promise<BasicActionResult>;
  resolveAppUpdateConflict: (appId: string) => Promise<{ runId: string; status: ChatRunStatus } | BasicActionResult>;
  uninstallApp: (appId: string) => Promise<BasicActionResult>;
  renameInstalledApp: (input: RenameInstalledAppInput) => Promise<RenameInstalledAppResult>;
  getAppDetails: (appId: string) => Promise<AppDetails | null>;
  listAppPrompts: (appId: string) => Promise<AppPromptReviewItem[]>;
  validateAppPrompt: (input: AppPromptReviewInput) => Promise<AppPromptValidationResult>;
  updateAppPrompt: (input: AppPromptReviewInput) => Promise<AppPromptMutationResult>;
  restoreAppPrompt: (input: AppPromptRestoreInput) => Promise<AppPromptMutationResult>;
  installWelcome: (appId: string, userLanguage?: string) => Promise<InstallWelcomeResult>;
  openApp: (appId: string, locale?: string) => Promise<OpenAppResult>;
  stopApp: (appId: string) => Promise<StopAppResult>;
  getAppRuntimeStatus: (appId: string) => Promise<RuntimeStatus>;
  startLocalNetworkShare: (appId: string) => Promise<LocalNetworkShareResult>;
  stopLocalNetworkShare: (appId: string) => Promise<LocalNetworkShareResult>;
  getLocalNetworkShareStatus: (appId: string) => Promise<LocalNetworkShareStatus>;
  startRemoteNetworkShare: (appId: string) => Promise<RemoteNetworkShareResult>;
  stopRemoteNetworkShare: (appId: string) => Promise<RemoteNetworkShareResult>;
  getRemoteNetworkShareStatus: (appId: string) => Promise<RemoteNetworkShareStatus>;
  getRemoteActivity: () => Promise<RemoteActivitySnapshot>;
  onRemoteActivityChanged: (listener: (event: RemoteActivitySnapshot) => void) => () => void;
  getAppSecrets: (appId: string) => Promise<AppSecretsState>;
  listUserSecrets: () => Promise<UserSecretSummary[]>;
  createUserSecret: (input: CreateUserSecretInput) => Promise<SecretMutationResult>;
  updateUserSecret: (input: UpdateUserSecretInput) => Promise<SecretMutationResult>;
  deleteUserSecret: (input: DeleteUserSecretInput) => Promise<SecretMutationResult>;
  connectAppSecret: (input: ConnectAppSecretInput) => Promise<SecretMutationResult>;
  disconnectAppSecret: (input: DisconnectAppSecretInput) => Promise<SecretMutationResult>;
  onInstallProgress: (listener: (event: { appId: string; progress: InstallAppResult }) => void) => () => void;
  onRuntimeStatusChanged: (listener: (event: RuntimeStatus) => void) => () => void;
  getSettings: () => Promise<Settings>;
  speechToTextGetState: () => Promise<SpeechToTextState>;
  speechToTextInstall: () => Promise<SpeechToTextState>;
  speechToTextStart: () => Promise<SpeechToTextState>;
  speechToTextStop: () => Promise<SpeechToTextState>;
  speechToTextUpdateConfig: (input: SpeechToTextConfigInput) => Promise<SpeechToTextState>;
  speechToTextPickAudio: () => Promise<{ canceled: boolean; path?: string }>;
  speechToTextProcess: (input: SpeechToTextProcessInput) => Promise<SpeechToTextProcessResult>;
  speechToTextProcessUpload: (input: SpeechToTextUploadInput) => Promise<SpeechToTextProcessResult>;
  speechToTextCreateRealtimeSession: () => Promise<SpeechToTextRealtimeSession>;
  microphonePermissionStatus: () => Promise<MicrophonePermissionStatus>;
  microphonePermissionRequest: () => Promise<MicrophonePermissionStatus>;
  liveVoiceInputGetState: () => Promise<LiveVoiceInputState>;
  liveVoiceInputUpdateConfig: (input: LiveVoiceInputConfigInput) => Promise<LiveVoiceInputState>;
  liveVoiceInputUpdateDevices: (input: LiveVoiceInputDeviceListInput) => Promise<LiveVoiceInputState>;
  liveVoiceInputCreateSession: (input: LiveVoiceInputSessionInput) => Promise<LiveVoiceInputSession>;
  liveVoiceInputStop: (input?: LiveVoiceInputStopInput) => Promise<LiveVoiceInputState>;
  liveVoiceInputWakeDetected: (input: Partial<LiveVoiceInputWakeEvent>) => Promise<LiveVoiceInputState>;
  liveVoiceInputWakeReady: (input: Partial<LiveVoiceInputWakeRuntime>) => Promise<LiveVoiceInputState>;
  liveVoiceInputWakeUnavailable: (input: Partial<LiveVoiceInputWakeRuntime>) => Promise<LiveVoiceInputState>;
  onLiveVoiceInputChanged: (listener: (event: LiveVoiceInputState) => void) => () => void;
  onLiveVoiceInputForgerWake: (listener: (event: LiveVoiceInputWakeEvent) => void) => () => void;
  wakeWordGetState: () => Promise<WakeWordState>;
  wakeWordInstall: () => Promise<WakeWordState>;
  wakeWordStart: () => Promise<WakeWordState>;
  wakeWordStop: () => Promise<WakeWordState>;
  wakeWordUpdateConfig: (input: WakeWordConfigInput) => Promise<WakeWordState>;
  wakeWordCreateSession: () => Promise<WakeWordSession>;
  wakeWordRecordReady: (input: Partial<WakeWordRuntime>) => Promise<WakeWordState>;
  wakeWordRecordUnavailable: (input: Partial<WakeWordRuntime>) => Promise<WakeWordState>;
  wakeWordRecordDetected: (input: { deviceId?: string; modelId?: string; confidence?: number }) => Promise<WakeWordState>;
  wakeWordRecordDiagnostic: (input: WakeWordDiagnosticEvent) => Promise<WakeWordState>;
  onWakeWordChanged: (listener: (event: WakeWordState) => void) => () => void;
  onWakeWordDetected: (listener: (event: WakeWordDetectionEvent) => void) => () => void;
  onAudioRuntimeBrokerRequest: (listener: (event: AudioRuntimeBrokerRequest) => void) => () => void;
  audioRuntimeBrokerRespond: (response: AudioRuntimeBrokerResponse) => Promise<void>;
  textToSpeechGetState: () => Promise<TextToSpeechState>;
  textToSpeechInstall: () => Promise<TextToSpeechState>;
  textToSpeechStart: () => Promise<TextToSpeechState>;
  textToSpeechStop: () => Promise<TextToSpeechState>;
  textToSpeechUpdateConfig: (input: TextToSpeechConfigInput) => Promise<TextToSpeechState>;
  textToSpeechSynthesize: (input: TextToSpeechSynthesizeInput) => Promise<TextToSpeechSynthesizeResult>;
  updateCodexDefaults: (input: UpdateCodexDefaultsInput) => Promise<Settings>;
  updateAgentDefaults: (input: UpdateAgentDefaultsInput) => Promise<Settings>;
  updateDeveloperMode: (input: UpdateDeveloperModeInput) => Promise<Settings>;
  updateAppDeveloperSettings: (input: UpdateAppDeveloperSettingsInput) => Promise<DeveloperPathState>;
  getDeveloperPathState: (appId?: string) => Promise<DeveloperPathState>;
  getDesktopUpdateState: () => Promise<DesktopUpdateState>;
  checkDesktopUpdates: () => Promise<DesktopUpdateState>;
  downloadDesktopUpdate: () => Promise<DesktopUpdateState>;
  installDesktopUpdate: () => Promise<DesktopUpdateState>;
  desktopUpdateQuitForInstall: () => Promise<{ success: true }>;
  onDesktopUpdateProgress: (listener: (event: DesktopUpdateState) => void) => () => void;
  getForgerAccount: () => Promise<ForgerAccountSession>;
  registerForgerAccount: (input: ForgerAccountRegisterInput) => Promise<ForgerAccountSession & { success: boolean; userMessage?: string; technicalCode?: string }>;
  loginForgerAccount: (input: ForgerAccountLoginInput) => Promise<ForgerAccountSession & { success: boolean; userMessage?: string; technicalCode?: string }>;
  loginForgerAccountWithGoogle: () => Promise<ForgerAccountSession & { success: boolean; userMessage?: string; technicalCode?: string }>;
  loginForgerAccountWithApple: () => Promise<ForgerAccountSession & { success: boolean; userMessage?: string; technicalCode?: string }>;
  updateForgerAccountProfile: (input: ForgerAccountProfileInput) => Promise<ForgerAccountSession & { success: boolean; userMessage?: string; technicalCode?: string }>;
  logoutForgerAccount: () => Promise<ForgerAccountSession & { success: boolean }>;
  onForgerAccountUpdated: (listener: (event: ForgerAccountSession & { userMessage?: string; technicalCode?: string }) => void) => () => void;
  getCloudStorageUsage: () => Promise<CloudStorageUsage | null>;
  getCloudDevices: () => Promise<CloudDevicesState>;
  registerCloudDevice: (input: { name: string }) => Promise<CloudDevicesState & { success: boolean }>;
  updateCloudDeviceName: (input: { name: string }) => Promise<CloudDevicesState & { success: boolean }>;
  unlinkMobileDeviceFromDesktop: (authorizationId: number) => Promise<CloudDevicesState & { success: boolean }>;
  generateDevicePairingCode: () => Promise<CloudDevicesState & { success: boolean }>;
  acceptMobilePairingRequest: (requestId: number) => Promise<CloudDevicesState & { success: boolean }>;
  rejectMobilePairingRequest: (requestId: number) => Promise<CloudDevicesState & { success: boolean }>;
  deleteMobilePairingRequest: (requestId: number) => Promise<CloudDevicesState & { success: boolean }>;
  listFriends: () => Promise<CloudFriendship[]>;
  listMySocialApps: () => Promise<SocialUserAppList>;
  uploadSocialApp: (input: SocialUserAppUploadInput) => Promise<{ success: boolean; app?: SocialUserApp; share?: SocialUserAppShare; userMessage?: string; technicalCode?: string }>;
  updateSocialApp: (input: SocialUserAppUpdateInput) => Promise<SocialUserApp>;
  updateSocialAppVisibility: (userAppId: number, visibility: Exclude<SocialUserAppVisibility, 'restricted'>) => Promise<SocialUserApp>;
  deleteSocialApp: (userAppId: number) => Promise<BasicActionResult>;
  createSocialAppShare: (userAppId: number) => Promise<SocialUserAppShare>;
  resolveSocialCode: (code: string) => Promise<{ app: SocialUserApp; share?: Record<string, unknown> }>;
  resolveSocialApp: (id: number) => Promise<{ app: SocialUserApp }>;
  getSocialProfile: (username: string) => Promise<SocialUserProfileDetail>;
  getSocialProfileUrl: (username: string) => Promise<string>;
  prepareSocialAppReview: (input: PrepareSocialAppReviewInput, locale?: string) => Promise<{ success: boolean; quarantine?: SocialAppQuarantineRecord; userMessage: string; technicalCode?: string }>;
  finishSocialAppInstall: (input: { quarantineId: string }, locale?: string) => Promise<InstallAppResult & { appId?: string }>;
  deleteQuarantinedSocialApp: (input: { quarantineId: string }, locale?: string) => Promise<{ success: boolean; userMessage: string; technicalCode?: string }>;
  installSocialApp: (input: { appId?: number; appSlug?: string; shareCode?: string; trustDecision?: 'not_reviewed' | 'reviewed' | 'skipped_review' }, locale?: string) => Promise<InstallAppResult & { appId?: string; download?: SocialUserAppDownload }>;
  searchFriends: (username: string) => Promise<CloudFriendUser[]>;
  sendFriendRequest: (username: string) => Promise<CloudFriendship>;
  acceptFriendRequest: (id: number) => Promise<CloudFriendship>;
  declineFriendRequest: (id: number) => Promise<CloudFriendship>;
  cancelFriendRequest: (id: number) => Promise<CloudFriendship>;
  markFriendChatRead: (friendUserId: number) => Promise<CloudFriendship>;
  openFriendChatWindow: (friendship: CloudFriendship) => Promise<FriendChatWindowOpenResult>;
  listCloudMessages: (friendUserId: number) => Promise<CloudMessage[]>;
  sendCloudMessage: (input: CloudSendMessageInput) => Promise<CloudMessage>;
  sendCloudAppShareMessage: (input: CloudSendAppShareInput) => Promise<CloudMessage>;
  decideAppMessagePermission: (cloudMessageId: number, decision: CloudAppMessagePermissionDecision) => Promise<CloudMessage>;
  getForumParticipation: () => Promise<ForumParticipationState>;
  updateForumParticipation: (action: 'mark_prompt_shown' | 'opt_in' | 'opt_out') => Promise<ForumParticipationState>;
  listForumPosts: (limit?: number) => Promise<ForumPost[]>;
  getForumPost: (id: number) => Promise<ForumPost>;
  createForumPost: (body: string) => Promise<ForumPost>;
  createForumComment: (postId: number, body: string) => Promise<ForumComment>;
  replyForumComment: (commentId: number, body: string) => Promise<ForumComment>;
  deleteForumPost: (id: number) => Promise<ForumPost>;
  deleteForumComment: (id: number) => Promise<ForumComment>;
  moderateForumPost: (id: number, action: 'hide' | 'unhide', reason?: string) => Promise<ForumPost>;
  moderateForumComment: (id: number, action: 'hide' | 'unhide', reason?: string) => Promise<ForumComment>;
  onCloudFriendshipEvent: (listener: (event: CloudSocialEvent) => void) => () => void;
  getCloudIdentity: () => Promise<CloudIdentityState>;
  revealCloudSecretKey: () => Promise<string>;
  regenerateCloudSecretKey: () => Promise<CloudIdentityState>;
  submitAppRating: (input: SubmitAppRatingInput) => Promise<{ success: boolean; rating?: AppRatingSummary; userMessage?: string; technicalCode?: string }>;
  submitProductFeedback: (input: SubmitProductFeedbackInput) => Promise<{ success: boolean; userMessage?: string; technicalCode?: string } & FailureDiagnosticFields>;
  submitUsageEvent: (input: SubmitUsageEventInput) => Promise<SubmitUsageEventResult>;
  openExternalUrl: (url: string) => Promise<{ success: boolean; userMessage?: string } & FailureDiagnosticFields>;
  getAgentProviderUsage: () => Promise<AgentProviderUsageResult>;
  listLlmProviderProfiles: () => Promise<LlmProviderProfilesState>;
  setActiveLlmProviderProfile: (input: SetActiveLlmProviderProfileInput) => Promise<SetActiveLlmProviderProfileResult>;
  updateLlmProviderProfileDefaults: (input: UpdateLlmProviderProfileDefaultsInput) => Promise<LlmProviderProfileMutationResult>;
  getCodexAuthStatus: () => Promise<CodexAuthStatus>;
  openCodexUsageDashboard: () => Promise<{ success: boolean; userMessage?: string } & FailureDiagnosticFields>;
  connectCodexAuth: () => Promise<{ success: boolean; userMessage: string } & FailureDiagnosticFields>;
  disconnectCodexAuth: () => Promise<{ success: boolean; userMessage: string } & FailureDiagnosticFields>;
  reinstallCodex: () => Promise<{ success: boolean; userMessage: string; status?: CodexAuthStatus } & FailureDiagnosticFields>;
  getClaudeAuthStatus: () => Promise<ClaudeAuthStatus>;
  confirmClaudeAuthConnection: () => Promise<{ success: boolean; userMessage: string; status: ClaudeAuthStatus } & FailureDiagnosticFields>;
  connectClaudeAuth: () => Promise<{ success: boolean; userMessage: string; status?: ClaudeAuthStatus } & FailureDiagnosticFields>;
  disconnectClaudeAuth: () => Promise<{ success: boolean; userMessage: string; status?: ClaudeAuthStatus } & FailureDiagnosticFields>;
  signOutClaudeAuth: () => Promise<{ success: boolean; userMessage: string; status?: ClaudeAuthStatus } & FailureDiagnosticFields>;
  reinstallClaude: () => Promise<{ success: boolean; userMessage: string; status?: ClaudeAuthStatus } & FailureDiagnosticFields>;
  getAntigravityAuthStatus: () => Promise<AntigravityAuthStatus>;
  connectAntigravityAuth: () => Promise<{ success: boolean; userMessage: string; status?: AntigravityAuthStatus } & FailureDiagnosticFields>;
  startAntigravityAuthSession: () => Promise<AntigravityAuthSessionStartResult & FailureDiagnosticFields>;
  writeAntigravityAuthSession: (input: { sessionId: string; input: string }) => Promise<{ success: boolean; userMessage?: string } & FailureDiagnosticFields>;
  cancelAntigravityAuthSession: (sessionId: string) => Promise<{ success: boolean; userMessage?: string } & FailureDiagnosticFields>;
  onAntigravityAuthSessionEvent: (listener: (event: AntigravityAuthSessionEvent) => void) => () => void;
  disconnectAntigravityAuth: () => Promise<{ success: boolean; userMessage: string; status?: AntigravityAuthStatus } & FailureDiagnosticFields>;
  reinstallAntigravity: () => Promise<{ success: boolean; userMessage: string; status?: AntigravityAuthStatus } & FailureDiagnosticFields>;
  prepareDesktopErrorReport: (input: DesktopErrorReportPreview) => Promise<DesktopErrorReportPreview>;
  submitDesktopErrorReport: (input: DesktopErrorReportPreview) => Promise<{ success: boolean; userMessage: string; technicalCode?: string }>;
  prepareConversationDiagnosticReport: (input: PrepareConversationDiagnosticReportInput) => Promise<ConversationDiagnosticReportPreview>;
  submitConversationDiagnosticReport: (input: ConversationDiagnosticReportPreview) => Promise<SubmitConversationDiagnosticReportResult>;
  onDesktopErrorReportRequested: (listener: (event: DesktopErrorReportPreview) => void) => () => void;
  desktopLog: (input: { level?: 'debug' | 'info' | 'warn' | 'error'; event: string; message?: string; context?: Record<string, unknown> }) => Promise<{ success: boolean }>;
  listAgentTools: (locale?: string) => Promise<AgentToolPackageDefinition[]>;
  getAgentToolSettings: () => Promise<AgentToolSettings>;
  updateAgentToolApproval: (input: UpdateAgentToolApprovalInput) => Promise<AgentToolSettings>;
  listOfficialTools: (locale?: string) => Promise<OfficialToolsState>;
  refreshOfficialTools: (locale?: string) => Promise<OfficialToolsState>;
  activateOfficialTool: (toolId: string, locale?: string) => Promise<ToolMutationResult>;
  configureOfficialTool: (input: ConfigureOfficialToolInput) => Promise<ToolMutationResult>;
  callOfficialTool: (input: CallOfficialToolInput) => Promise<CallOfficialToolResult>;
  deactivateOfficialTool: (toolId: string, locale?: string) => Promise<ToolMutationResult>;
  connectionsList: (locale?: string) => Promise<ConnectionsState>;
  connectionsConfigure: (input: ConfigureConnectionInput) => Promise<ConnectionMutationResult>;
  connectionsDisconnect: (input: DisconnectConnectionInput) => Promise<ConnectionMutationResult>;
  connectionsCall: (input: CallConnectionActionInput) => Promise<CallConnectionActionResult>;
  connectionsSetDefault: (input: { type: string; connectionId: string }) => Promise<ConnectionMutationResult>;
  onOfficialToolEvent: (listener: (event: OfficialToolRuntimeEvent) => void) => () => void;
  getAppToolsInstallGate: (appId: string, locale?: string, options?: GetAppToolsInstallGateOptions) => Promise<AppToolsInstallGate | null>;
  setAppToolGrant: (input: SetAppToolGrantInput, locale?: string) => Promise<AppToolsInstallGate | null>;
  memoryList: (input?: MemoryListInput) => Promise<MemoryEntry[]>;
  memoryCreate: (input: MemoryCreateInput) => Promise<MemoryEntry>;
  memoryUpdate: (input: MemoryUpdateInput) => Promise<MemoryEntry>;
  memoryDelete: (id: string) => Promise<{ success: boolean }>;
  getLlmRunsSnapshot: () => Promise<LlmRunsSnapshot>;
  onLlmRunsSnapshotChanged: (listener: (snapshot: LlmRunsSnapshot) => void) => () => void;
  personalAgentsList: () => Promise<PersonalAgent[]>;
  personalAgentsCreate: (input: PersonalAgentCreateInput) => Promise<PersonalAgent>;
  personalAgentGrantOptionsList: () => Promise<PersonalAgentGrantOptions>;
  personalAgentUpdatePermissions: (input: PersonalAgentUpdatePermissionsInput) => Promise<PersonalAgent>;
  personalAgentsDelete: (input: PersonalAgentDeleteInput) => Promise<{ success: boolean }>;
  personalAgentConversationsList: (input: PersonalAgentConversationsListInput) => Promise<PersonalAgentConversation[]>;
  personalAgentWorkspaceList: (input: PersonalAgentWorkspaceListInput) => Promise<PersonalAgentWorkspaceEntry[]>;
  personalAgentWorkspaceFileRead: (input: PersonalAgentWorkspaceFileReadInput) => Promise<PersonalAgentWorkspaceFile>;
  personalAgentWorkspaceFileWrite: (input: PersonalAgentWorkspaceFileWriteInput) => Promise<PersonalAgentWorkspaceFile>;
  personalAgentStartConversation: (input: PersonalAgentConversationStartInput) => Promise<PersonalAgentConversation>;
  personalAgentSendMessage: (input: PersonalAgentMessageSendInput) => Promise<PersonalAgentConversation>;
  personalAgentGetConversation: (input: PersonalAgentConversationGetInput) => Promise<PersonalAgentConversation | null>;
  personalAgentPeerThreadsList: (input: PersonalAgentPeerThreadsListInput) => Promise<PersonalAgentPeerThread[]>;
  personalAgentPeerThreadGet: (input: PersonalAgentPeerThreadGetInput) => Promise<PersonalAgentPeerThread | null>;
  onPersonalAgentConversationEvent: (listener: (event: PersonalAgentConversationEvent) => void) => () => void;
  chatStartRun: (input: ChatStartRunInput) => Promise<{ runId: string; status: ChatRunStatus }>;
  chatGetRun: (input: ChatGetRunInput) => Promise<ChatRun | null>;
  chatCancelRun: (input: ChatCancelRunInput) => Promise<{ success: boolean }>;
  chatApprovePermission: (input: ChatApprovePermissionInput) => Promise<{ success: boolean }>;
  chatApplyRun: (input: ChatApplyRunInput) => Promise<ChatApplyResult>;
  chatUndo: (input: ChatUndoInput) => Promise<ChatUndoResult>;
  traceChatEvent: (event: RendererChatTraceEvent) => Promise<{ success: boolean }>;
  onChatRunUpdated: (listener: (event: ChatRunEvent) => void) => () => void;
  filesPickForChat: () => Promise<PickedChatFile[]>;
  filesStageForChat: (input: FilesStageForChatInput) => Promise<PickedChatFile>;
  filesDiscardStagedForChat: (input: FilesDiscardStagedForChatInput) => Promise<FilesActionResult>;
  filesList: (input?: FilesListInput) => Promise<ForgerFileRecord[]>;
  filesListCategories: () => Promise<ForgerFileCategory[]>;
  filesCreateCategory: (input: FilesCreateCategoryInput) => Promise<ForgerFileCategory>;
  filesRenameCategory: (input: FilesRenameCategoryInput) => Promise<FilesActionResult>;
  filesDeleteCategory: (input: FilesDeleteCategoryInput) => Promise<FilesActionResult>;
  filesImport: (input: FilesImportInput) => Promise<ForgerFileRecord[]>;
  filesMove: (input: FilesMoveInput) => Promise<ForgerFileRecord[]>;
  filesRename: (input: FilesRenameInput) => Promise<ForgerFileRecord>;
  filesDelete: (input: FilesDeleteInput) => Promise<FilesActionResult>;
  dbListTables: (appId: string) => Promise<DbListTablesResponse>;
  dbQueryTable: (appId: string, tableName: string, limit?: number) => Promise<DbQueryTableResponse>;
  automationsList: () => Promise<Automation[]>;
  automationsCreate: (input: AutomationUpsertInput) => Promise<Automation>;
  automationsUpdate: (input: AutomationUpsertInput & { id: string }) => Promise<Automation>;
  automationsDelete: (id: string) => Promise<FilesActionResult>;
  automationsPause: (id: string) => Promise<Automation>;
  automationsResume: (id: string) => Promise<Automation>;
  automationsRunNow: (id: string) => Promise<AutomationRunSummary>;
  automationsListRuns: (automationId: string) => Promise<AutomationRunSummary[]>;
  automationsGetRunTranscript: (runId: string) => Promise<AutomationRun | null>;
  onAutomationUpdated: (listener: (event: { automation: Automation; run?: AutomationRunSummary }) => void) => () => void;
  workflowsList: () => Promise<Workflow[]>;
  workflowsUpsert: (input: WorkflowUpsertInput) => Promise<Workflow>;
  workflowsDelete: (id: string) => Promise<FilesActionResult>;
  workflowsSetEnabled: (id: string, enabled: boolean) => Promise<Workflow>;
  workflowsRunNow: (id: string) => Promise<WorkflowRunSummary>;
  workflowsRunNode: (workflowId: string, nodeId: string) => Promise<WorkflowRunSummary>;
  workflowsCancelRun: (runId: string) => Promise<FilesActionResult>;
  workflowsApproveNode: (input: WorkflowApproveNodeInput) => Promise<FilesActionResult>;
  workflowsListRuns: (workflowId: string) => Promise<WorkflowRunSummary[]>;
  workflowsGetRun: (runId: string) => Promise<WorkflowRun | null>;
  onWorkflowUpdated: (listener: (event: WorkflowUpdatedEvent) => void) => () => void;
  backgroundTasksList: () => Promise<BackgroundTask[]>;
  backgroundTaskGet: (id: string) => Promise<BackgroundTask | null>;
  backgroundTasksUpsert: (input: BackgroundTaskUpsertInput) => Promise<BackgroundTask>;
  onBackgroundTaskUpdated: (listener: (event: BackgroundTaskEvent) => void) => () => void;
  minimizeWindow: () => Promise<void>;
  toggleMaximizeWindow: () => Promise<WindowControlState>;
  closeWindow: () => Promise<void>;
  getWindowState: () => Promise<WindowControlState>;
  onWindowStateChanged: (listener: (state: WindowControlState) => void) => () => void;
  onDeepLink: (listener: (link: ForgerDeepLink) => void) => () => void;
}

/**
 * Structured representation of a `forger://` URL delivered to the
 * renderer. The shape mirrors the parser in `main/deep-links.ts`. Add
 * new variants as more deep-link kinds are introduced.
 */
export type ForgerDeepLink =
  | {
      kind: 'chat';
      /** Manifest name of the target app (`pyme-os`). Renderer resolves it against the installed list. `null` means the global free chat. */
      app: string | null;
      /** Composer text to prefill, when provided by the URL. */
      prompt: string | null;
      /** The raw URL, for logging / debugging. */
      raw: string;
    }
  | {
      kind: 'social-app';
      code: string | null;
      id: number | null;
      raw: string;
    }
  | {
      kind: 'social-profile';
      username: string;
      raw: string;
    }
  | {
      kind: 'unknown';
      raw: string;
    };
