export const copy = {
  es: {
    title: 'WhatsApp',
    webSearch: 'Permitir búsquedas en internet',
    webHelp: 'Busca información en la web pública. Las consultas pueden enviarse al proveedor de búsqueda. Este permiso no comparte tus archivos ni memorias privados.',
    webEnableAgent: 'Primero activa Agentes → este agente → Ajustes → Permitir internet.',
    webRetained: 'La elección guardada se conserva, pero las búsquedas no están disponibles mientras el permiso general esté desactivado. Se reactivan si vuelves a permitir internet al agente.',
    webAllowed: 'Búsquedas en internet: Permitidas', webOff: 'Búsquedas en internet: Desactivadas', webUnavailable: 'Búsquedas en internet: No disponibles — internet del agente desactivado',
    access: 'Quién puede pedir tareas', owner: 'Solo yo (cuenta vinculada)', selected: 'Personas seleccionadas', all: 'Todos los miembros del grupo',
    accessHelp: 'La cuenta vinculada siempre puede pedir tareas y es la única que puede activar o pausar al agente.',
    allHelp: 'Incluye a quienes se incorporen al grupo.',
    chooseParticipants: 'Elige al menos una persona o selecciona Solo yo.', groupOnly: 'Todos los miembros solo está disponible en grupos.',
    replyPreview: 'Así se verán las respuestas', exampleReply: 'Respuesta de ejemplo',
    connections: 'Abrir Conexiones', reconnect: 'Reconectar',
    description: 'El agente responde en los chats que habilites aquí, con la información y acciones que compartes explícitamente. Este canal requiere Codex o Claude.',
    noConnection: 'Conecta WhatsApp desde Conexiones para usar este canal.',
    noChats: 'Todavía no hay conversaciones disponibles. Envía un mensaje en WhatsApp y actualiza la lista.',
    bindings: 'Chats configurados',
    add: 'Agregar chat',
    edit: 'Editar',
    account: 'Cuenta de WhatsApp',
    chat: 'Chat',
    search: 'Buscar por nombre o número',
    openChats: 'Abrir conversaciones', clearChat: 'Quitar selección',
    noMatches: 'No hay conversaciones que coincidan.', chatsLoading: 'Cargando conversaciones…',
    refresh: 'Actualizar chats',
    alias: 'Palabra de activación',
    aliasHelp: 'Se aplica a todos los chats de este agente en la cuenta. Escríbela seguida de una tarea.',
    purpose: 'Propósito en este chat',
    purposeHelp: 'Obligatorio para activar el agente.',
    scope: 'Instrucciones de trabajo para este chat',
    scopeHelp: 'Guía las tareas de este chat. El acceso real se limita a la información y acciones seleccionadas abajo.',
    participants: 'Personas que pueden pedirle tareas',
    participantsHelp: 'Cada persona autorizada solo utiliza la información y acciones seleccionadas abajo.',
    enabled: 'Permitir respuestas automáticas en este chat',
    commands: (alias: string) => `Desde la cuenta vinculada, escribe “${alias} ON” para activar el chat o “${alias} OFF” para detenerlo. Las tareas empiezan con “${alias}” o “@${alias}”. Las tareas nuevas esperan su turno. Para corregir tu tarea, envía “${alias} CORREGIR MI ULTIMA corrección”. Corregir o cancelar no deshace acciones ya realizadas. Forger debe permanecer abierto y conectado.`,
    save: 'Guardar chat',
    saved: 'Configuración guardada.',
    delete: 'Quitar chat',
    deleted: 'Chat quitado.',
    removeConfirm: '¿Quitar este chat del agente? Se detendrá el trabajo activo.',
    active: 'Activo',
    disconnected: 'Habilitado · sin conexión',
    pause: 'Pausar', activity: 'Ver actividad', history: 'Abrir conversación completa', close: 'Cerrar', cancel: 'Cancelar',
    retry: 'Reintentar', participantsFailed: 'No pude cargar las personas. Reintenta para elegir quién puede pedir tareas.', participantsLoading: 'Cargando personas…',
    audience: 'Las respuestas y la información compartida son visibles para todos en este chat, incluso quienes no pueden pedir tareas.',
    reviewSave: 'Revisar acceso del chat', confirmSave: 'Aplicar configuración',
    aliasWarning: 'Esta palabra se aplica a todos los chats de este agente y cuenta. Guardar cambia la palabra en los siguientes chats; las tareas activas continúan:',
    currentSettings: 'Configuración actual', useDraft: 'Conservar mi borrador y revisar',
    enableSummary: 'No se comparten archivos ni memorias personales por defecto.',
    delivery: 'Entrega', execution: 'Tarea', request: 'Solicitud', reply: 'Respuesta completa',
    cancelRequest: 'Cancelar tarea', dismiss: 'Descartar', retryDelivery: 'Reintentar entrega',
    unknownHelp: 'WhatsApp podría haber recibido esta respuesta. No se reenvía automáticamente para evitar duplicados.',
    emptyActivity: 'Todavía no hay solicitudes.', activityFailed: 'No pude cargar la actividad. Reintenta.', actionFailed: 'No pude completar esta acción. Actualiza la actividad y reintenta.',
    cancelHelp: 'Cancelar no deshace acciones ya realizadas.',

    inactive: 'Pausado',
    working: 'Trabajando',
    review: 'Invocación pendiente',
    sent: 'Última respuesta enviada',
    deliveryFailed: 'Última respuesta falló',
    deliveryUnknown: 'Entrega sin confirmar',
    connectionMissing: 'La cuenta ya no está disponible.',
    loadFailed: 'No pude cargar la configuración de WhatsApp.',
    chatsFailed: 'No pude cargar las conversaciones.',
    saveFailed: 'No pude guardar este chat.',
    conflict: 'La configuración cambió en otro lugar. Tu borrador se conserva. Revisa la configuración actual antes de aplicar tu borrador.',
    deleteFailed: 'No pude quitar este chat.',
    chooseChat: 'Elige una cuenta y una conversación.',
    purposeRequired: 'Escribe el propósito antes de activar las respuestas.',
    aliasRequired: 'Escribe una palabra de activación.',
    aliasConflict: 'Otro agente ya usa esa palabra de activación en esta cuenta.',
  },
  en: {
    title: 'WhatsApp',
    webSearch: 'Allow web searches',
    webHelp: 'Searches the public web. Queries may be sent to the search provider. This permission does not share your private files or memories.',
    webEnableAgent: 'First enable Agents → this agent → Settings → Allow internet.',
    webRetained: 'Your saved choice is retained, but searches are unavailable while the agent permission is off. They become available again if you allow agent internet access.',
    webAllowed: 'Web searches: Allowed', webOff: 'Web searches: Off', webUnavailable: 'Web searches: Unavailable — agent internet is off',
    access: 'Who can assign tasks', owner: 'Only me (linked account)', selected: 'Selected people', all: 'Everyone in the group',
    accessHelp: 'The linked account can always assign tasks and is the only one that can activate or pause the agent.',
    allHelp: 'Includes people who join the group later.',
    chooseParticipants: 'Choose at least one person, or select Only me.', groupOnly: 'Everyone is available only for groups.',
    replyPreview: 'Reply preview', exampleReply: 'Example response',
    connections: 'Open Connections', reconnect: 'Reconnect',
    description: 'The agent responds in chats you enable here, with the information and actions you explicitly share. This channel requires Codex or Claude.',
    noConnection: 'Connect WhatsApp in Connections to use this channel.',
    noChats: 'No conversations available yet. Send a message in WhatsApp and refresh the list.',
    bindings: 'Configured chats',
    add: 'Add chat',
    edit: 'Edit',
    account: 'WhatsApp account',
    chat: 'Chat',
    search: 'Search by name or number',
    openChats: 'Open conversations', clearChat: 'Clear selection',
    noMatches: 'No matching conversations.', chatsLoading: 'Loading conversations…',
    refresh: 'Refresh chats',
    alias: 'Activation word',
    aliasHelp: 'Applies to every chat for this agent and account. Type it followed by a task.',
    purpose: 'Purpose in this chat',
    purposeHelp: 'Required before enabling the agent.',
    scope: 'Work instructions for this chat',
    scopeHelp: 'Guides tasks in this chat. Actual access is limited to the information and actions selected below.',
    participants: 'People allowed to assign tasks',
    participantsHelp: 'Each allowed person uses only the information and actions selected below.',
    enabled: 'Allow automatic replies in this chat',
    commands: (alias: string) => `From the linked account, send “${alias} ON” to activate this chat or “${alias} OFF” to stop it. Tasks start with “${alias}” or “@${alias}”. New tasks wait in order. To correct your task, send “${alias} CORREGIR MI ULTIMA correction”. Corrections and cancellation do not undo actions already taken. Forger must remain open and connected.`,
    save: 'Save chat',
    saved: 'Settings saved.',
    delete: 'Remove chat',
    deleted: 'Chat removed.',
    removeConfirm: 'Remove this chat from the agent? Active work will stop.',
    active: 'Active',
    disconnected: 'Enabled · disconnected',
    pause: 'Pause', activity: 'View activity', history: 'Open full conversation', close: 'Close', cancel: 'Cancel',
    retry: 'Retry', participantsFailed: 'Could not load participants. Retry to choose who can assign tasks.', participantsLoading: 'Loading participants…',
    audience: 'Replies and any shared information are visible to everyone in this chat, including people who cannot assign tasks.',
    reviewSave: 'Review chat access', confirmSave: 'Apply settings',
    aliasWarning: 'This activation word applies to every chat for this agent and account. Saving changes the activation word in the following chats; active tasks continue:',
    currentSettings: 'Current settings', useDraft: 'Keep my draft and review',
    enableSummary: 'No personal files or memories are shared by default.',
    delivery: 'Delivery', execution: 'Task', request: 'Request', reply: 'Complete response',
    cancelRequest: 'Cancel task', dismiss: 'Dismiss', retryDelivery: 'Retry delivery',
    unknownHelp: 'WhatsApp may already have received this reply. Automatic resend is disabled to avoid duplicates.',
    emptyActivity: 'No requests yet.', activityFailed: 'Could not load activity. Retry.', actionFailed: 'Could not complete this action. Refresh activity and try again.',
    cancelHelp: 'Canceling does not undo actions already taken.',

    inactive: 'Paused',
    working: 'Working',
    review: 'Pending invocation',
    sent: 'Last reply sent',
    deliveryFailed: 'Last reply failed',
    deliveryUnknown: 'Delivery unconfirmed',
    connectionMissing: 'The account is no longer available.',
    loadFailed: 'Could not load WhatsApp settings.',
    chatsFailed: 'Could not load conversations.',
    saveFailed: 'Could not save this chat.',
    conflict: 'Settings changed elsewhere. Your draft is preserved. Review the current settings before applying your draft.',
    deleteFailed: 'Could not remove this chat.',
    chooseChat: 'Choose an account and a conversation.',
    purposeRequired: 'Enter a purpose before enabling replies.',
    aliasRequired: 'Enter an activation word.',
    aliasConflict: 'Another agent already uses this activation word on this account.',
  },
} as const;

export type ChannelCopy = typeof copy.en | typeof copy.es;

export const webAccessSummary = (c: ChannelCopy, selected: boolean, agentAllowed: boolean) =>
  selected ? agentAllowed ? c.webAllowed : c.webUnavailable : c.webOff;
